In [1]:
import numpy as np
# buat numpy jadi np(var)

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
type(np.array(my_list))

In [5]:
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros(10).shape
# shape untuk jadi 2 dimensi

(10,)

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
np.linspace(0, 10, 30)
# 0 = start, 10 = akhir, 30 = jumlah matrix


array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [49]:
np.eye(4)
# identitas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.seed(7)
# mempertahankan probabilitas ke-7
# harus di taro di shell yang sama
np.random.rand(5,5)

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923],
       [0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837]])

In [31]:
np.random.randn(2)

array([0.79418452, 1.17666305])

In [34]:
np.random.randint(1,100)
# random angka integer antara 1-100

32

In [35]:
np.random.randint(1,100, 10)
# 10 = banyaknya angka di dalam list

array([94, 45, 93, 72, 24, 11, 36, 65, 62,  8])

In [36]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr

array([23, 28, 32, 21, 36, 35, 33,  3, 27, 33])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([23, 28, 32, 21, 36, 35, 33,  3, 27, 33])

In [46]:
ranarr.max()
# terbesar
ranarr.min()
# terkecil

3

In [47]:
ranarr.argmax()
# mencari index angka terbesar
ranarr.argmin()

7

In [60]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# SLIDE 2

In [64]:
import numpy as np

In [67]:
arr = np.arange(11, 20)

In [68]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
arr[-6:-2]
# dari belakang ke depan

array([14, 15, 16, 17])

In [70]:
arr + 10
# untuk nambahin semua angka dalam list +10

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [78]:
arr[0:5]= 100
# mengubah 5 index pertama jadi 100

In [79]:
arr

array([100, 100, 100, 100, 100,  16,  17,  18,  19])

In [80]:
slice_of_arr = arr[0:6]

In [81]:
slice_of_arr

array([100, 100, 100, 100, 100,  16])

In [126]:
slice_of_arr[5 :] = 99

In [127]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [128]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
arr_copy = arr.copy()
# jadi list yang original tidak terpengaruh
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
arr_copy[1:5] = 50
# mengganti index 1 sampai 5 jadi 50

In [131]:
arr_copy

array([ 1, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [102]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [104]:
arr_2d.shape
# (vertical,Horizontal)
# (row,column)

(3, 3)

In [108]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [114]:
arr_2d[:,2]
# semua kolom ke 3 (2+1)

array([15, 30, 45])

In [110]:
arr_2d[1,0] = 100
# mengganti index

In [111]:
arr_2d

array([[  5,  10,  15],
       [100,  25,  30],
       [ 35,  40,  45]])

In [115]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [116]:
arr_length = arr2d.shape[0]
arr_length

10

In [117]:
for i in range(arr_length):
    arr2d[i] = i
#     mengganti [i] jadi i
    
arr2d    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [118]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
arr[arr > 4]
# tampilkan angka yang lebih dari 4

array([ 5,  6,  7,  8,  9, 10])

In [121]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [124]:
mat[[3,2,0]]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

# SLIDE 3

In [ ]:
import numpy as np
arr = np.arange(1,10)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.argmax(arr)
# untuk mengetahui dimana index nilai terbesar

9